[alias.SpecialAbstraction]
body = """

    //@ public invariant this.c == this.absVal;
    //@ public invariant this.ref == this.absValRef;

    private int c;
    private SpecialAbstraction ref;
"""
init = """

    this.c = 0;
    this.ref = null;

    //@ set this.absVal = 0;
    //@ set this.absValRef = null;
    //@ set fp = this.*;
"""
getRef = """

    return this.ref;
"""
getValue = """

    return this.c;
"""
setRef = """

    this.ref = value;
    //@ set this.absValRef = value;
"""
setValue = """

    this.c = value;
    //@ set this.absVal = value;
"""
looseInfo = ""
file = ""

[alias._Client]

file = """
package alias;

public class _Client {

  /*@ normal_behavior
    requires true;
    ensures true;
    */
  public static void main(String[] args) 
  {
    client();
  }

  /*@ normal_behavior
    requires true;
    ensures true;
  */
  public static void client() 
  {
  }
}
"""
